config:
  target: "http://localhost:3000"
  plugins:
    metrics-by-endpoint:
      # Group metrics by endpoint
      stripQueryString: true
      ignoreUnknownEndpoints: false
      metricsNamespace: "artillery_metrics"
  
  # Load testing phases
  phases:
    # Warm-up phase
    - duration: 30
      arrivalRate: 5
      name: "Warm up"
    
    # Ramp up phase
    - duration: 60
      arrivalRate: 5
      rampTo: 50
      name: "Ramp up load"
    
    # Sustained load phase
    - duration: 120
      arrivalRate: 50
      name: "Sustained load"
    
    # Spike test
    - duration: 30
      arrivalRate: 100
      name: "Spike test"

  # Default settings
  http:
    timeout: 10
  
  # Performance thresholds
  ensure:
    maxErrorRate: 1  # Max 1% error rate
    p95: 500  # 95th percentile response time should be under 500ms
    p99: 1000  # 99th percentile response time should be under 1000ms

  # Variables for dynamic testing
  variables:
    testEmail: "test{{ $randomNumber() }}@example.com"
    testPassword: "TestPassword123!"

# Default scenario (basic health check)
scenarios:
  - name: "Health Check Scenario"
    weight: 10
    flow:
      - get:
          url: "/api/health"
          capture:
            - json: "$.status"
              as: "healthStatus"
